### ISSUE TITLE
The Wild, Wild West

### ISSUE THREAD

**Issue by RaycatWhoDat** [soleo/peapod-hackathon#1]
# I propose these ideas:

- [ ] Google Assistant-based ordering (not focused on the input as much as the formatting and versatility)
- [ ] Peapod CLI (I just wanna pipe a file into ```peapod``` and order stuff)
- [ ] Wasm-based toolchain/product
- [ ] Assisted development environment setup (think [Ninite](http://ninite.com) but curses-based)
- [ ] [insert interesting language stack here]
- [ ] Kotlin-based mobile app (if possible)
- [ ] Wifi-based context service (when device connects to wifi, do a thing)
- [ ] Desktop integration, Electron-based or otherwise
- [ ] Peapod ordering server (another way to integrate Peapod stuff)
- [ ] Kitchen status service (has something gone bad, etc.)

**Comment by soleo** [comment]
Great ideas. I will add them soon.

**Comment by soleo** [comment]
merged in the main list. @RaycatRakittra , I still need some explanations of what some of items really means.
